### ISSUE TITLE
Доработать отрисовку unicode символов в gFont

### ISSUE THREAD

**Issue by FreeCX** [pinecrew/golos#3]
![2015-08-21_16 58 33_1366x768](https://cloud.githubusercontent.com/assets/1357744/9409862/ecf68524-4825-11e5-9f25-edc9ea5844ab.png)
Варианты решения проблемы с отрисовкой [unicode](https://github.com/pinecrew/golos/tree/unicode)
- определить размер символа и правильно его отрисовать
- использовать специализированные типы: string & etc
- унифицировать размер символа

**Comment by citrux** [comment]
Я правильно понял, что ты `char` на `wchar_t` поменял и всё сразу стало плохо? А то там сходу непонятно, в чём проблема.

**Comment by FreeCX** [comment]
Проблема в том что английские символы, цифры и знаки  кодируются как `char`, а все другие как расширенные -- 2 байта или более. А я все символы под одну гребёнку загоняю и использую списки для отрисовки с размером `GL_UNSIGNED_SHORT` вместо старого `GL_UNSIGNED_BYTE`, да и подготовка глифов идёт по два байта для всех символов.
